{"name": "Verify AddBook API functionality -- @1.1 ", "status": "broken", "statusDetails": {"message": "AttributeError: 'DBHelpers' object has no attribute 'conn'\n", "trace": "  File \"C:\\Users\\vibhor.agrawal\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\vibhor.agrawal\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_impl.py\", line 82, in step_impl\n    tp = BookApi().get_Book_detail(course_name)\n  File \"C:\\Users\\vibhor.agrawal\\PycharmProjects\\ApiDemo\\CommonMethod\\BookApi.py\", line 10, in get_Book_detail\n    return  self.db_heler.execute_select(sql)\n  File \"C:\\Users\\vibhor.agrawal\\PycharmProjects\\ApiDemo\\DbHelper.py\", line 40, in execute_select\n    self.conn.close()\n"}, "steps": [{"name": "Given the Book details with kjf842v and 28618", "status": "passed", "start": 1674212955357, "stop": 1674212955357}, {"name": "When we execute the AddBook PostAPI method", "status": "passed", "steps": [{"name": "Log (INFO) Params: {'name': 'Learn Python Automation with BDD', 'isbn': 'kjf842v', 'aisle': '28618', 'author': 'Vibhor GL'}", "status": "passed", "start": 1674212955358, "stop": 1674212955358}], "start": 1674212955357, "stop": 1674212955438}, {"name": "Then book is successfully added", "status": "broken", "statusDetails": {"message": "AttributeError: 'DBHelpers' object has no attribute 'conn'\n", "trace": "  File \"C:\\Users\\vibhor.agrawal\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\vibhor.agrawal\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\steps_impl.py\", line 82, in step_impl\n    tp = BookApi().get_Book_detail(course_name)\n  File \"C:\\Users\\vibhor.agrawal\\PycharmProjects\\ApiDemo\\CommonMethod\\BookApi.py\", line 10, in get_Book_detail\n    return  self.db_heler.execute_select(sql)\n  File \"C:\\Users\\vibhor.agrawal\\PycharmProjects\\ApiDemo\\DbHelper.py\", line 40, in execute_select\n    self.conn.close()\n"}, "steps": [{"name": "Log (ERROR) Failed running sql SELECT * FROM  Books WHERE BookName = 'Selenium';. Error: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)", "status": "passed", "start": 1674212959600, "stop": 1674212959600}], "start": 1674212955438, "stop": 1674212959603}], "parameters": [{"name": "isbn", "value": "kjf842v"}, {"name": "aisle", "value": "28618"}], "start": 1674212955356, "stop": 1674212959683, "uuid": "acf37c49-3832-451d-8192-81689a16f1a9", "historyId": "614bbca7a2a21bd013212a988361ce5f", "fullName": "General GET and POST functional test: Verify AddBook API functionality", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "library"}, {"name": "feature", "value": "General GET and POST functional test"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}